---
- name: Converge
  hosts: all
  become: true

  vars:
    n8n_version: "latest"
    n8n_port: 5678
    n8n_basic_auth_active: true
    n8n_basic_auth_user: "testuser"
    n8n_basic_auth_password: "testpass123"

  roles:
    - role: n8n
